// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/SeveranceDinnerPartyInvite-Fr5EE2/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-Fr5EE2/DinnerPartyPosterSeverance.tsx")
};
